config/routes.rb
Rails.application.routes.draw do
  

  resources :categories
  resources :blogs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @categories = Category.all

    cate = params[:cate]

    if !cate.nil?
      @blogs = Blog.where(:category_id => cate)
    else
      @blogs = Blog.all
    end

  
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.create(blog_params)


    if @blog.save
      redirect_to @blog
    else
      render :new
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])

    if @blog.update(blog_params)
      redirect_to @blog
    else
      render :edit
    end
  end

  def destroy
    @blog = Blog.find(params[:id])

    @blog.destroy
    redirect_to :action => :index
  end


  private

  def blog_params
    params.require(:blog).permit(:title, :content, :category_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/blogs/_form.html.erb
<div class="flex-row d-flex justify-content-center">

<div class="col-md-8">
<div class="card mt-5">

    <div class="card-body">
    <%= form_for @blog do |f| %>

    
    <div class="form-group">
    <%= f.label :title%>
    <%= f.text_field :title, class: 'form-control' %>
    
    </div>

    <div class="form-group">

    
    <%= f.label :content%>
    <%= f.text_area :content, class: 'form-control'%>

    </div>

    <div class="form-group">

    <%= f.select :category_id, Category.all.map {|c| [c.category, c.id]} %>

    </div>

    <%= f.submit "Create Blog", class: 'btn btn-outline-primary' %>
    <%= link_to "Back", blogs_path, class: 'btn btn-outline-secondary' %>

<% end %>

    </div>
</div>


</div>

</div>

app/views/blogs/edit.html.erb
<%= render 'form'%>

app/views/blogs/index.html.erb
<div class="container">
    <div class="row">

    
    <div class="col-md-8">

    <div class="row">
    
   
     <% @blogs.each do |blog| %>
        <div class="col-md-6">
            <div class="card mt-3">
                <div class="card-body">
                                    <h3><%= link_to blog.title, blog_path(blog.id) %></h3>

                    <%= link_to "View", blog_path(blog.id), class: 'btn btn-primary'%>
                </div>
            </div>
            
        </div>
                <% end %>

                 </div>
    </div>

   

    <div class="col-md-4">


    <div class="card mt-3">
        <div class="card-header">
            Categories
        </div>

        <div class="card-body">

        <ul class="list-group">

         <% @categories.each do |category| %>

        
  <li class="list-group-item d-flex justify-content-between align-items-center">
               <%= link_to category.category, blogs_path(:cate => category.id) %>

    <span class="badge badge-primary badge-pill"><%= category.blogs.count %></span>
  </li>
       <% end %>


        </ul>
        </div>
    
    </div>
     
    </div>
       


       
 </div>

 
    </div>

</div>

app/views/blogs/new.html.erb
<%= render 'form' %>

app/views/blogs/show.html.erb
<div class="container-fluid mt-3">
<h1>Category: <%= @blog.category.category %></h1>
<h3><%= @blog.title %></h3>


<p><%= @blog.content %></p>


<%= link_to "Edit", edit_blog_path(@blog.id), class: 'btn btn-primary' %>
<%= link_to "Delete", blog_path(@blog.id), method: :delete, class: 'btn btn-danger' %>
<%= link_to "Back", blogs_path, class: 'btn btn-secondary'%>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @category.category %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">BlogWithCategories</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-md-auto">
      <li class="nav-item active">
<%= link_to "Create Blog", new_blog_path, class: 'nav-link' %>

      </li>
      
  </div>
</nav>
    <%= yield %>
  </body>
</html>